server:
  port: 9000

spring:
  application:
    name: security-service

  profiles:
    active: dev, commons-jpa

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/tetravex
    username: postgres
    password: postgres