spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tetravex
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximumPoolSize: 2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  main:
    banner-mode: off

  application:
    name: "tetravex"

server:
  port: 8080