server:
  port: 8083

spring:

  profiles:
    active: eureka, swagger, commons-jpa

  application:
    name: comment-service

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/tetravex
    username: postgres
    password: postgres