server:
  port: 8081

spring:

  profiles:
    active: eureka, swagger, commons-jpa, security

  application:
    name: rating-service

  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/tetravex
    username: postgres
    password: postgres

  jpa:
    show-sql: true

debug: true

