spring:
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: okta-client-id
            client-secret: okta-client-secret
            authorization-grant-type: authorization_code
            scope: read,write
            redirect-uri: http://localhost:8081/api/v1/rating/tetravex

        provider:
          okta:
            authorization-uri: http://localhost:9000/api/v1/authenticate
            token-uri: http://localhost:9000/api/v1/authenticate
            user-info-uri: http://localhost:9000/api/v1/authenticate
            user-name-attribute: sub
            jwk-set-uri: http://localhost:9000/api/v1/authenticate
            issuer-uri: http://localhost:9000/api/v1/authenticate
            user-info-authentication-method: http://localhost:9000/api/v1/authenticate

