server:
  port: 8761

spring:
  application:
    name: eureka-server

  main:
    banner-mode: off

eureka:

  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    preferIpAddress: true

#management:
#  endpoint:
#    health:
#      show-details: always
#    shutdown:
#      enabled: true